# Short bio or description (displayed in the header)
title: Richard's Blog
name: Richard Groß
user_description: IT Archaeologist
profile_pic: /assets/img/profile.jpg
favicon: /assets/img/favicon.ico
copyright_name: Richard Groß
url: # the base hostname & protocol for your site e.g. "https://richargh.de"
baseurl: "" # the subpath of your site, e.g. "/blog"
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-asciidoc

sass:
  style: compressed

collections:
  notes:
    output: true
    permalink: /notes/:title

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
